### Update `r params$state` meta-data

The use of higher-level functions included in the `SGP` package (e.g. `analyzeSGP`)
requires the availability of state specific assessment information.  This meta-data
is compiled in a `R` object named `SGPstateData` that is housed in the package.

#### Knots and boundaries
Cubic B-spline basis functions are used in the calculation of SGPs to more
adequately model the heteroscedasticity and non-linearity found in assessment
data.^[It should be noted that the independent estimation of the regression
functions can potentially result in the crossing of the quantile functions.  This
occurs near the extremes of the distributions and is potentially more likely to
occur given the use of non-linear functions.  A potential result of allowing the
quantile functions to cross would be *lower* percentile estimations of growth for
*higher* observed scale scores at the extremes (give all else equal in prior
scores) and vice versa.  In order to deal with these contradictory estimates,
quantile regression results are isotonized to prevent quantile crossing following
the methods derived by Chernozhukov, Fernandez-Val and Glichon [-@chernozhukov2010quantile].]  
These functions require the selection of boundary and interior knots.  Boundary
knots (i.e. "boundaries") are end-points outside of the scale score distribution
that anchor the B-spline basis.  These are typically selected by extending the
entire range of scale scores by 10%.  That is, they are defined as lying 10%
below the lowest obtainable/observed scale score (LOSS) and 10% above the highest
obtainable/observed scale score (HOSS).  The interior knots (i.e. "knots") are
the *internal* breakpoints that define the spline.  The default choice in the
`SGP` package is to select the `r ord(20)`, `r ord(40)`, `r ord(60)` and
`r ord(80)` quantiles of the observed scale score distribution.

In general the knots and boundaries are computed from a distribution comprised
of several years of test data (i.e. multiple cohorts combined) so that any
irregularities in a single year are smoothed out.  This is important because
subsequent annual analyses use these same knots and boundaries as well.  All
defaults were used to compile the knots and boundaries for all tests from
previous years.

#### Proficiency level cutscores
Cutscores are set externally by the `r params$state` state officials through
standard-setting processes.  These data are mainly required for student growth
projections and growth targets.

####  Other meta-data of interest
...
...
...
