## Model Fit Plots

Using all available`r if(params$eoct.tf)){" EOG and EOC"}` test scores as the
variables, estimation of student growth percentiles was conducted for each possible
student (those with a current score and at least one prior score). Each analysis
is defined by the grade and content area for the grade-level analyses and exact
content area (and grade when relevant) sequences for the EOC subjects. `r if(!is.null(params$sgp.cohort.size){
  paste(params$state, "has added an additional requirement that an analysis
  cohort must have at least", prettyNum(params$sgp.cohort.size, big.mark=","),
  "students in order to calculate SGPs.")}`A goodness of fit plot is produced for
each unique analysis run in `r params$year``r if (!is.null(params$appendix)) {
  " and are all provided in Appendix A to this report"}`.

As an example, Figure `r getCounter("figure")+1` shows the results for
`r if (params$good.fit.example.grade != "EOCT") {paste(params$good.fit.example.grade, "<sup>th</sup> grade")}`
`r params$good.fit.example.subject` as an example of good model fit.  Figure
`r getCounter("figure")+2` is an example of minor model misfit from the
`r if (params$misfit.example.grade != "EOCT") {paste(params$misfit.example.grade, "<sup>th</sup> grade")}`
`r misfit.example.subject`.

The two panels compare the observed conditional density of the SGP estimates with
the theoretical (uniform) density.  The bottom left panel shows the empirical
distribution of SGPs given prior scale score deciles in the form of a 10 by 10
cell grid.  Percentages of student growth percentiles between the 10<sup>th</sup>,
20<sup>th</sup>, 30<sup>th</sup>, 40<sup>th</sup>, 50<sup>th</sup>, 60<sup>th</sup>,
70<sup>th</sup>, 80<sup>th</sup>, and 90<sup>th</sup> percentiles were calculated
based upon the empirical decile of the cohort's prior year scaled score
distribution^[The total students in each analysis varies depending on grade and
subject, and prior score deciles are based only on scores for students used in
the SGP calculations.].  With an infinite population of test takers, at each prior
scaled score, with perfect model fit, the expectation is to have 10 percent of
the estimated growth percentiles between 1 and 9, 10 and 19, 20 and 29, ..., and
90 and 99.  Deviations from 10 percent, indicated by red and blue shading,
suggests lack of model fit.  The further *above* 10 the darker the red, and the
further *below* 10 the darker the blue.  

When large deviations occur, one likely cause is a clustering of scale scores
that makes it impossible to "split" the score at a dividing point forcing a
majority of the scores into an adjacent cell.  This occurs more often in lowest
grade levels where fewer prior scores are available (particularly in the lowest
grade when only a single prior is available).  Another common cause of this is
small cohort size (e.g. fewer than 5,000 students).  Smaller cohorts generally
have less variability in most cases, which makes differentiating between students
more difficult.

The bottom right panel of each plot is a Q-Q plot which compares the observed
distribution of SGPs with the theoretical (uniform) distribution.  An ideal plot
here will show black step function lines that do not deviate greatly from the
ideal, red line which traces the 45 degree angle of perfect fit.

```{r, cache=TRUE, echo=FALSE, include=FALSE, GOFplots}
  ##    Create goodness of fit plots for tech report example
	dir.create(file.path("assets", "img"), recursive=TRUE, showWarnings=FALSE)
  setwd(file.path("assets", "img"))

  setkeyv(sgp_object@Data, SGP:::getKey(sgp_object))

  add.cohort.tf <- (params$sgp.type != "SGP" & any(grepl("^SGP$", names(sgp_object@Data))))
  if (add.cohort.tf) sgps.to.use <- c("SGP", params$sgp.type) else sgps.to.use <- params$sgp.type
  if (any(grepl("SIMEX", sgps.to.use))) sgps.to.use <- unique(c(sgps.to.use, "SGP_SIMEX", "SGP_SIMEX_RANKED"))

  ###  Good Model Fit
  gof.data <- sgp_object@Data[VALID_CASE=="VALID_CASE" & !is.na(SGP) & YEAR == params$sgp.year &
                              CONTENT_AREA == params$good.fit.example.subject & GRADE == params$good.fit.example.grade,
                               c("VALID_CASE", "CONTENT_AREA", "GRADE", "YEAR", "ID", sgps.to.use, # "ACHIEVEMENT_LEVEL_PRIOR",
                                 "SCALE_SCORE", "SCALE_SCORE_PRIOR", "SGP_NORM_GROUP"), with=FALSE]
  if (!is.null(params$good.fit.example.norm.group)) {
    gof.data <- gof.data[SGP_NORM_GROUP %in% params$good.fit.example.norm.group]
  } else {
    if (params$good.fit.example.grade == "EOCT") {
      gof.data[, SGP_NORM_GROUP := paste0(params$sgp.year, "/", params$good.fit.example.subject, "_", params$good.fit.example.grade)]
    }
  }
	for(sgp_type in sgps.to.use) {
    gofSGP(gof.data, state=params$state.abv, years=params$sgp.year, content_areas=params$good.fit.example.subject,
           use.sgp=sgp_type, ceiling.floor= FALSE, output.format="PNG") # change placeFigure to substitute PNG/PDF for HTML/PDF output?
  }
  setwd("Goodness_of_Fit")
  dir.create("good_fit", recursive=TRUE, showWarnings=FALSE)
  if (all(file.copy(list.dirs(recursive = FALSE) %w/o% c(file.path(".", "good_fit"), file.path(".", "misfit")), "good_fit", recursive = TRUE))) {
    file.remove(grep("misfit|good_fit", list.files(recursive = TRUE), value=TRUE, invert=TRUE), recursive=TRUE)
    file.remove(grep("misfit|good_fit", list.dirs(recursive = FALSE), value=TRUE, invert=TRUE), recursive=TRUE)
  }
  setwd("..")

  ###  Poor(er) Model Fit
  gof.data <- sgp_object@Data[VALID_CASE=="VALID_CASE" & !is.na(SGP) & YEAR == params$sgp.year &
                              CONTENT_AREA == params$misfit.example.subject & GRADE == params$misfit.example.grade,
                               c("VALID_CASE", "CONTENT_AREA", "GRADE", "YEAR", "ID", sgps.to.use, # "ACHIEVEMENT_LEVEL_PRIOR",
                                 "SCALE_SCORE", "SCALE_SCORE_PRIOR", "SGP_NORM_GROUP"), with=FALSE]
  if (!is.null(params$misfit.example.norm.group)) {
    gof.data <- gof.data[SGP_NORM_GROUP %in% params$misfit.example.norm.group]
  } else  {
    if (params$misfit.example.grade == "EOCT") {
      gof.data[, SGP_NORM_GROUP := paste0(params$sgp.year, "/", params$misfit.example.subject, "_", params$misfit.example.grade)]
    }
  }
  for(sgp_type in sgps.to.use) {
    gofSGP(gof.data, state=params$state.abv, years=params$sgp.year, content_areas=params$misfit.example.subject,
           use.sgp=sgp_type, ceiling.floor= FALSE, output.format="PNG") # change placeFigure to substitute PNG/PDF for HTML/PDF output?
  }
  setwd("Goodness_of_Fit")
  dir.create("misfit", recursive=TRUE, showWarnings=FALSE)
  if (all(file.copy(list.dirs(recursive = FALSE) %w/o% c(file.path(".", "good_fit"), file.path(".", "misfit")), "misfit", recursive = TRUE))) {
    file.remove(grep("misfit|good_fit", list.files(recursive = TRUE), value=TRUE, invert=TRUE), recursive=TRUE)
    file.remove(grep("misfit|good_fit", list.dirs(recursive = FALSE), value=TRUE, invert=TRUE), recursive=TRUE)
  }

	setwd(file.path("..", "..", ".."))
```
